server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此配置要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，用于与binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 通道名称
          destination: studyExchange # 要使用的exchange名称
          content-type: application/json # 消息类型
          binder: defaultRabbit # 要绑定的消息服务的具体设置
          group: atguiguB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认30s）
    lease-expiration-duration-in-seconds: 5 # 超时时间（默认90s）
    instance-id: receive-8803.com # 在信息列表显示主机名称
    prefer-ip-address: true # 访问的路径变为IP地址