server:
  port: 3344

spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuizhigang78/springcloud-config.git # 仓库链接
          search-paths: # 搜索目录
            - springcloud-config
      label: master # 读取分支

  # rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      # 单机
      defaultZone: http://localhost:7001/eureka

## rabbitmq相关配置,暴露 bus 刷新配置的端点
management:
  endpoints: # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'