server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务进行路由，uri也需要相应调整
      routes:
        - id: payment_route # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址 lb代表load balance
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 # 过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id，值为1024
          predicates:
            - Path=/payment/lb/**
            # - After=2020-06-02T00:06:23.808+08:00[Asia/Shanghai] # ZonedDateTimeTest.java
            # - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            # - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
            # - Cookie=username, zzyy # Cookie=chocolate, ch.p cookie name + 正则表达式
            #- Header=X-Request-Id, \d+
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      # 单机
      defaultZone: http://eureka7001.com:7001/eureka
      # 集群
      #defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka